### ISSUE TITLE
XML Package Builder

### ISSUE THREAD

**Issue by benstrl** [grebmann1/sfdx-ui-light#14]
**Is your feature request related to a problem? Please describe.**
As I don't often use VS Code, this feature can be handy.

**Describe the solution you'd like**
I want a way to create a XML Package and the possibility to decide what it contains freely. 

**Describe alternatives you've considered**
As an alternative, I can use a VS Code Extension.

**Comment by grebmann1** [comment]
Delivered under the "Deploy/Retrieve" module.
