### ISSUE TITLE
Suppresses Toast Messages

### ISSUE THREAD

**Issue by JeroenSfdc** [grebmann1/sfdx-ui-light#23]
**Describe the bug**
With the SF Toolkit extension enabled (either incognito or not), toast messages are being suppressed. 

**To Reproduce**
1. Enable toe SF Toolkit extension for Incognito
2. Open Console and run following:

```
var toastEvent = $A.get("e.force:showToast");
        toastEvent.setParams({
            title : 'My toast',
            message: 'Awkwardly, a clumsy and dizzy Boring Bob, eager to impress, flustered the grumpy crowd. Hasty and irritated, they watched him jumpy and kooky, lazily attempting a moody speech. Nervous, he made odd jokes, perplexing the quirky audience, who grew restless. Silly as ever, Bob tired quickly, feeling unlucky, vague, and wobbly, before delivering an extra-weird, yawning finish that left everyone feeling zany.',
            duration: 5000,
            key: 'info_alt',
            type: 'success',
            mode: 'pester'
        });
        toastEvent.fire();
```

**Expected behavior**
Toast message should be shown. 

**Screenshots**
There are not errors reported, neither in the Chrome developer tools console.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: `Version 130.0.6723.70 (Official Build) (x86_64)`

**Additional context**
This issue started happening a while ago, might be that it relates with W25 release of Salesforce. 
It's a blocking issue to effectively use the SF Toolkit app.

**Comment by grebmann1** [comment]
@JeroenSfdc I have deployed a fix. It shouldn't happen anymore.
