### ISSUE TITLE
Add keyboard shortcut for executing query

### ISSUE THREAD

**Issue by pkassios** [grebmann1/sfdx-ui-light#25]
Currently in the query editor, after writing the query you need to click on the "Run" button to execute it.
It would be great to be able to define a keyboard shortcut for doing this i.e. a usual shortcut is Ctrl - Enter.

**Comment by grebmann1** [comment]
Will be deployed in 1.3.21
The new feature include the following shortcuts :

-  CTRL/CMD + ENTER to run (Data Explorer, Anonymous Apex,API Explorer)
-  CTRL/CMD + S to save (Data Explorer, Anonymous Apex)
